theme: jekyll-theme-cayman

title: Sequoyah Council Wood Badge
description: "April 7-9 and April 21-23, 2017"

# TODO: remove this before deploying to custom domain!
baseurl: /scwoodbadge.org

gems:
  - jekyll-feed
